= PILE Base: pPool
:source-highlighter: rouge
:linkcss:
:toc: macro
:toclevels: 5

include::snippets/header.adoc[]


(**This module is experimental.** Please see the xref:p_pool.adoc#_module_notes[Module Notes] at the end of this page.)

__pPool__ creates stacks of pooled resources (usually tables or userdata).

Dependencies: xref:p_assert.adoc[pAssert], xref:p_name.adoc[pName]

[source,lua]
----
local pPool = require("p_pool")

local function _popping(r)
	if not r then r = {} end
	r[1], r[2], r[3], r[4] = 0, 0, 0, 0
	return r
end

local function _pushing(r)
	if type(r) ~= "table" then error("expected table") end
	return r
end

local threshold = 5

local stack = pPool.new(_popping, _pushing, threshold)

-- get a resource
local color1 = stack:pop()

-- (do stuff with 'color1')

-- return the resource to the stack
color1 = stack:push(color1) -- 'color1' is now nil
----


toc::[]


== API: pPool (The Module)

=== pPool.new

Creates a new pool stack.

[source,lua]
----
local stack = pPool.new([popping], [pushing], [threshold])
----

* `[popping]`: __(false)__ The initialization function, for creating new resources or refreshing old ones. It takes one argument for the resource (which may be `nil` if the stack is empty), and returns the resource.

* `[pushing]`: __(false)__ The cleanup function, for winding down resources before they are returned to the stack or discarded. It takes one argument for the resource, and returns the resource (or `nil` to discard it).

* `[threshold]`: __(0)__ How many resources to hold in the stack before pushed resources are simply discarded.

**Returns:** The new pool stack.


[discrete]
==== Notes

The default `threshold` of zero will always keep the pool stack empty.


== API: Pool (The Object)


=== Pool:getThreshold

Gets the pool stack's current threshold.

[source,lua]
----
local threshold = Pool:getThreshold()
----

**Returns:** The threshold number.

'''


=== Pool:pop

Retrieves or creates a new resource.

[source,lua]
----
local r = Pool:pop()
----

**Returns:** The new or used resource.

'''


=== Pool:push

Pushes a resource onto the stack (or discards it if the stack is full).

[source,lua]
----
Pool:push(r)
----

* `r`: The resource to push.

'''


=== Pool:reduceStack

Discards a certain number of resources in the stack.

[source,lua]
----
Pool:reduceStack(n)
----

* `n`: __(0)__ Resources above this index are discarded.

'''


=== Pool:setThreshold

Sets the pool stack's threshold (at what size it should begin to discard pushed resources). A value of zero makes the stack discard all resources.

[source,lua]
----
Pool:setThreshold(threshold)
----

* `threshold`: The threshold number.


== Module Notes

Some __do__'s and __don't__s and other tips:

* When you push a resource onto a pool stack, you must __not__ continue to use it through any existing references.

* Do not push the same resource onto a pool stack multiple times.

* Junk fields in tables will persist across pushes and pops, unless you go out of your way to clean them (which leads to more overhead).

* Rather than push extremely large arrays, you can discard them in the 'pushing' callback by returning `nil`.

* If you suspect that pooling is causing trouble, you can effectively disable pool stacks by setting their threshold numbers to zero.


include::snippets/footer.adoc[]
