= PILE Base: pUtf8Conv
:source-highlighter: rouge
:linkcss:
:toc: macro
:toclevels: 5

include::snippets/header.adoc[]


__pUtf8Conv__ contains auxiliary functions for converting UTF-16 and ISO 8859-1 (Latin 1) to UTF-8 and back.

Dependencies: xref:p_assert.adoc[pAssert], xref:p_interp.adoc[pInterp], xref:p_name.adoc[pName], xref:p_utf8.adoc[pUtf8]

// Text encoding conversions are not well illustrated by an example here, IMO.


toc::[]


== API


=== pUtf8Conv.fromLatin1ToUtf8

Converts a Latin 1 (ISO 8859-1) string to UTF-8.

[source,lua]
----
pUtf8Conv.fromLatin1ToUtf8(s)
----

* `s`: The Latin 1 string to convert.

**Returns:** The converted UTF-8 string, or `nil`, error string, and byte index if there was a problem.

'''


=== pUtf8Conv.fromUtf16ToUtf8

Converts a UTF-16 string to UTF-8.

[source,lua]
----
pUtf8Conv.fromUtf16ToUtf8(s, [big_en])
----

* `s`: The UTF-16 string to convert.

* `[big_en]`: __(nil)__ `true` if the input UTF-16 string is big-endian, `false`/`nil` if it is little-endian.

**Returns:** The converted UTF-8 string, or `nil`, error string, and byte index if there was a problem.

'''


=== pUtf8Conv.fromUtf8ToLatin1

Converts a UTF-8 string to Latin 1 (ISO 8859-1).

Only code points 0 through 255 can be directly mapped to a Latin 1 string. Use the `[unmapped]` argument to control what happens when an unmappable code point is encountered.

[source,lua]
----
pUtf8Conv.fromUtf8ToLatin1(s, [unmapped])
----

* `s`: The UTF-8 string to convert.

* `[unmapped]`: When `unmapped` is a string, it is used in place of unmappable code points. (Pass in an empty string to ignore unmappable code points.) When `unmapped` is any other type, the function returns `nil`, an error string, and the byte where the unmappable code point was encountered.

**Returns:** The converted Latin 1 string, or `nil`, error string, and byte index if there was a problem.

'''


=== pUtf8Conv.fromUtf8ToUtf16

Converts a UTF-8 string to UTF-16.

[source,lua]
----
pUtf8Conv.fromUtf8ToUtf16(s, [big_en])
----

* `s`: The UTF-8 string to convert.

* `[big_en]`: __(nil)__ `true` if the converted UTF-16 string is big-endian, `false`/`nil` if it is little-endian.

**Returns:** The converted UTF-16 string, or `nil`, error string, and byte index if there was a problem.


include::snippets/footer.adoc[]
